services:
  db:
    image: postgres:15-alpine
    container_name: 
    restart: always
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: fasteat-back
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  frontend:
    build: ./frontend
    container_name: fasteat-front
    ports:
      - "5173:80"
    depends_on:
      - backend
