services:
  db:
    image: postgres:15-alpine
    container_name: fasteat-db
    restart: always
    environment:
      POSTGRES_DB: fasteat_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: fasteat-back
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fasteat_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
  frontend:
    build: ./frontend
    container_name: fasteat-front
    ports:
      - "5173:80"
    depends_on:
      - backend